require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe ColorSchemesController do

  # This should return the minimal set of attributes required to create a valid
  # ColorScheme. As you add validations to ColorScheme, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) { {  } }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ColorSchemesController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all color_schemes as @color_schemes" do
      color_scheme = ColorScheme.create! valid_attributes
      get :index, {}, valid_session
      assigns(:color_schemes).should eq([color_scheme])
    end
  end

  describe "GET show" do
    it "assigns the requested color_scheme as @color_scheme" do
      color_scheme = ColorScheme.create! valid_attributes
      get :show, {:id => color_scheme.to_param}, valid_session
      assigns(:color_scheme).should eq(color_scheme)
    end
  end

  describe "GET new" do
    it "assigns a new color_scheme as @color_scheme" do
      get :new, {}, valid_session
      assigns(:color_scheme).should be_a_new(ColorScheme)
    end
  end

  describe "GET edit" do
    it "assigns the requested color_scheme as @color_scheme" do
      color_scheme = ColorScheme.create! valid_attributes
      get :edit, {:id => color_scheme.to_param}, valid_session
      assigns(:color_scheme).should eq(color_scheme)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new ColorScheme" do
        expect {
          post :create, {:color_scheme => valid_attributes}, valid_session
        }.to change(ColorScheme, :count).by(1)
      end

      it "assigns a newly created color_scheme as @color_scheme" do
        post :create, {:color_scheme => valid_attributes}, valid_session
        assigns(:color_scheme).should be_a(ColorScheme)
        assigns(:color_scheme).should be_persisted
      end

      it "redirects to the created color_scheme" do
        post :create, {:color_scheme => valid_attributes}, valid_session
        response.should redirect_to(ColorScheme.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved color_scheme as @color_scheme" do
        # Trigger the behavior that occurs when invalid params are submitted
        ColorScheme.any_instance.stub(:save).and_return(false)
        post :create, {:color_scheme => {  }}, valid_session
        assigns(:color_scheme).should be_a_new(ColorScheme)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        ColorScheme.any_instance.stub(:save).and_return(false)
        post :create, {:color_scheme => {  }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested color_scheme" do
        color_scheme = ColorScheme.create! valid_attributes
        # Assuming there are no other color_schemes in the database, this
        # specifies that the ColorScheme created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        ColorScheme.any_instance.should_receive(:update).with({ "these" => "params" })
        put :update, {:id => color_scheme.to_param, :color_scheme => { "these" => "params" }}, valid_session
      end

      it "assigns the requested color_scheme as @color_scheme" do
        color_scheme = ColorScheme.create! valid_attributes
        put :update, {:id => color_scheme.to_param, :color_scheme => valid_attributes}, valid_session
        assigns(:color_scheme).should eq(color_scheme)
      end

      it "redirects to the color_scheme" do
        color_scheme = ColorScheme.create! valid_attributes
        put :update, {:id => color_scheme.to_param, :color_scheme => valid_attributes}, valid_session
        response.should redirect_to(color_scheme)
      end
    end

    describe "with invalid params" do
      it "assigns the color_scheme as @color_scheme" do
        color_scheme = ColorScheme.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ColorScheme.any_instance.stub(:save).and_return(false)
        put :update, {:id => color_scheme.to_param, :color_scheme => {  }}, valid_session
        assigns(:color_scheme).should eq(color_scheme)
      end

      it "re-renders the 'edit' template" do
        color_scheme = ColorScheme.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        ColorScheme.any_instance.stub(:save).and_return(false)
        put :update, {:id => color_scheme.to_param, :color_scheme => {  }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested color_scheme" do
      color_scheme = ColorScheme.create! valid_attributes
      expect {
        delete :destroy, {:id => color_scheme.to_param}, valid_session
      }.to change(ColorScheme, :count).by(-1)
    end

    it "redirects to the color_schemes list" do
      color_scheme = ColorScheme.create! valid_attributes
      delete :destroy, {:id => color_scheme.to_param}, valid_session
      response.should redirect_to(color_schemes_url)
    end
  end

end
