require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe RepeatingEventsController do

  # This should return the minimal set of attributes required to create a valid
  # RepeatingEvent. As you add validations to RepeatingEvent, be sure to
  # adjust the attributes here as well.
  before(:each) do
    @category_group = CategoryGroup.create!(description: "category group")
    @category = Category.create!(description: "category", category_group_id: @category_group.id)
  end
  
  let(:valid_attributes) { { "title" => "MyString",  :category_id => @category.id, :repetition_type => "weekly", :on_sunday => true} }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # RepeatingEventsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET index" do
    it "assigns all repeating_events as @repeating_events" do
      repeating_event = RepeatingEvent.create! valid_attributes
      get :index, {}, valid_session
      assigns(:repeating_events).should eq([repeating_event])
    end
  end

  describe "GET show" do
    it "assigns the requested repeating_event as @repeating_event" do
      repeating_event = RepeatingEvent.create! valid_attributes
      get :show, {:id => repeating_event.to_param}, valid_session
      assigns(:repeating_event).should eq(repeating_event)
    end
  end

  describe "GET new" do
    it "assigns a new repeating_event as @repeating_event" do
      get :new, {}, valid_session
      assigns(:repeating_event).should be_a_new(RepeatingEvent)
    end
  end

  describe "GET edit" do
    it "assigns the requested repeating_event as @repeating_event" do
      repeating_event = RepeatingEvent.create! valid_attributes
      get :edit, {:id => repeating_event.to_param}, valid_session
      assigns(:repeating_event).should eq(repeating_event)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new RepeatingEvent" do
        expect {
          post :create, {:repeating_event => valid_attributes}, valid_session
        }.to change(RepeatingEvent, :count).by(1)
      end

      it "assigns a newly created repeating_event as @repeating_event" do
        post :create, {:repeating_event => valid_attributes}, valid_session
        assigns(:repeating_event).should be_a(RepeatingEvent)
        assigns(:repeating_event).should be_persisted
      end

      it "redirects to the created repeating_event" do
        post :create, {:repeating_event => valid_attributes}, valid_session
        response.should redirect_to(RepeatingEvent.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved repeating_event as @repeating_event" do
        # Trigger the behavior that occurs when invalid params are submitted
        RepeatingEvent.any_instance.stub(:save).and_return(false)
        post :create, {:repeating_event => { "title" => "invalid value" }}, valid_session
        assigns(:repeating_event).should be_a_new(RepeatingEvent)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        RepeatingEvent.any_instance.stub(:save).and_return(false)
        post :create, {:repeating_event => { "title" => "invalid value" }}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested repeating_event" do
        repeating_event = RepeatingEvent.create! valid_attributes
        # Assuming there are no other repeating_events in the database, this
        # specifies that the RepeatingEvent created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        RepeatingEvent.any_instance.should_receive(:update).with({ "title" => "MyString" })
        put :update, {:id => repeating_event.to_param, :repeating_event => { "title" => "MyString" }}, valid_session
      end

      it "assigns the requested repeating_event as @repeating_event" do
        repeating_event = RepeatingEvent.create! valid_attributes
        put :update, {:id => repeating_event.to_param, :repeating_event => valid_attributes}, valid_session
        assigns(:repeating_event).should eq(repeating_event)
      end

      it "redirects to the repeating_event" do
        repeating_event = RepeatingEvent.create! valid_attributes
        put :update, {:id => repeating_event.to_param, :repeating_event => valid_attributes}, valid_session
        response.should redirect_to(repeating_event)
      end
    end

    describe "with invalid params" do
      it "assigns the repeating_event as @repeating_event" do
        repeating_event = RepeatingEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RepeatingEvent.any_instance.stub(:save).and_return(false)
        put :update, {:id => repeating_event.to_param, :repeating_event => { "title" => "invalid value" }}, valid_session
        assigns(:repeating_event).should eq(repeating_event)
      end

      it "re-renders the 'edit' template" do
        repeating_event = RepeatingEvent.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        RepeatingEvent.any_instance.stub(:save).and_return(false)
        put :update, {:id => repeating_event.to_param, :repeating_event => { "title" => "invalid value" }}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested repeating_event" do
      repeating_event = RepeatingEvent.create! valid_attributes
      expect {
        delete :destroy, {:id => repeating_event.to_param}, valid_session
      }.to change(RepeatingEvent, :count).by(-1)
    end

    it "redirects to the repeating_events list" do
      repeating_event = RepeatingEvent.create! valid_attributes
      delete :destroy, {:id => repeating_event.to_param}, valid_session
      response.should redirect_to(repeating_events_url)
    end
  end

end
